homeassistant:
  container_name: homeassistant
  image: homeassistant/home-assistant:{{ hass_version }}
  depends_on:
    - adguard
    - deconz
  restart: unless-stopped
  environment:
    - PUID={{ global.user_id }}
    - PGID={{ global.group_id }}
    - TZ={{ global.timezone }}
  network_mode: host
  ports:
    - 8123:8123
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - {{ global.docker_volume }}/homeassistant/config:/config
    - {{ global.docker_volume }}/homeassistant/data:/data
    - {{ global.docker_volume }}/homeassistant/logs/home-assistant.log:/config/home-assistant.log
    - {{ global.docker_volume }}/homeassistant/logs/home-assistant.log.1:/config/home-assistant.log.1
    - {{ global.docker_volume }}/homeassistant/logs/home-assistant.log.fault:/config/home-assistant.log.fault
  devices:
    - /dev/ttyUSB-RFLINK:/dev/rflink
  healthcheck:
    test: python -m homeassistant --config /config --script check_config && wget --no-verbose --tries=1 --spider http://localhost:8123
    interval: 15s
    timeout: 10s
  labels:
    - "traefik.enable=true"
    - "traefik.http.services.hass.loadbalancer.server.port=8123"
    - "traefik.http.routers.hass-internal.service=hass"
    - "traefik.http.routers.hass-internal.entrypoints=internal"
    - "traefik.http.routers.hass-internal.rule=Host(`hass.{{ global.server.domain }}`)"
    - "traefik.http.routers.hass-external.service=hass"
    - "traefik.http.routers.hass-external.entrypoints=external"
    - "traefik.http.routers.hass-external.rule=Host(`{{ hass.domain }}`)"
    - "traefik.http.routers.hass-external.tls=true"
    - "traefik.http.routers.hass-external.tls.certresolver=letsencrypt"
    # Allow NL, internal IPs, and Toon
    - "traefik.http.middlewares.hass-geoip.forwardauth.address=http://localhost:8000/?locations=NL&ips=127.0.0.1,10.0.0.0/8,52.210.253.108,52.48.198.78,52.49.253.220"
    - "traefik.http.routers.hass-external.middlewares=hass-geoip@docker"
